/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiAttachmentChip: typeof import('./src/components/AiAttachmentChip.vue')['default']
    AiAttachmentPreview: typeof import('./src/components/AiAttachmentPreview.vue')['default']
    AppDetailModal: typeof import('./src/components/AppDetailModal.vue')['default']
    AssistantBadge: typeof import('./src/components/AssistantBadge.vue')['default']
    AssistantPicker: typeof import('./src/components/AssistantPicker.vue')['default']
    AvatarUpload: typeof import('./src/components/AvatarUpload.vue')['default']
    ChatSidebar: typeof import('./src/components/ChatSidebar.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    CreateAiDialog: typeof import('./src/components/CreateAiDialog.vue')['default']
    CreateGroupDialog: typeof import('./src/components/CreateGroupDialog.vue')['default']
    FileMessage: typeof import('./src/components/FileMessage.vue')['default']
    FilePreviewModal: typeof import('./src/components/FilePreviewModal.vue')['default']
    FileUploadButton: typeof import('./src/components/FileUploadButton.vue')['default']
    GomokuBoard: typeof import('./src/components/GomokuBoard.vue')['default']
    GomokuChat: typeof import('./src/components/GomokuChat.vue')['default']
    InviteUserDialog: typeof import('./src/components/InviteUserDialog.vue')['default']
    LivePreview: typeof import('./src/components/LivePreview.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MentionInput: typeof import('./src/components/MentionInput.vue')['default']
    MentionList: typeof import('./src/components/MentionList.vue')['default']
    MentionNotification: typeof import('./src/components/MentionNotification.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetRemarkDialog: typeof import('./src/components/SetRemarkDialog.vue')['default']
    ToastNotification: typeof import('./src/components/ToastNotification.vue')['default']
  }
}
