/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAiConfig: typeof import('./src/components/AdminAiConfig.vue')['default']
    AppDetailModal: typeof import('./src/components/AppDetailModal.vue')['default']
    AvatarUpload: typeof import('./src/components/AvatarUpload.vue')['default']
    ChatSidebar: typeof import('./src/components/ChatSidebar.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    CreateAiDialog: typeof import('./src/components/CreateAiDialog.vue')['default']
    CreateGroupDialog: typeof import('./src/components/CreateGroupDialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FileMessage: typeof import('./src/components/FileMessage.vue')['default']
    FilePreviewModal: typeof import('./src/components/FilePreviewModal.vue')['default']
    FileUploadButton: typeof import('./src/components/FileUploadButton.vue')['default']
    GomokuBoard: typeof import('./src/components/GomokuBoard.vue')['default']
    GomokuChat: typeof import('./src/components/GomokuChat.vue')['default']
    InviteUserDialog: typeof import('./src/components/InviteUserDialog.vue')['default']
    LivePreview: typeof import('./src/components/LivePreview.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MentionInput: typeof import('./src/components/MentionInput.vue')['default']
    MentionList: typeof import('./src/components/MentionList.vue')['default']
    MentionNotification: typeof import('./src/components/MentionNotification.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetRemarkDialog: typeof import('./src/components/SetRemarkDialog.vue')['default']
    SystemMetrics: typeof import('./src/components/admin/SystemMetrics.vue')['default']
    ToastNotification: typeof import('./src/components/ToastNotification.vue')['default']
    UserTable: typeof import('./src/components/admin/UserTable.vue')['default']
  }
}
